language: c
compiler:
  - gcc
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
script:
# compile the engine
  - cd build/cmake && cmake . && make
# todo: run the tests 
